# Build stage
FROM node:16-alpine as build

WORKDIR /app
COPY package*.json ./
# Remplacer npm ci par npm install
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM node:16-alpine
WORKDIR /app
COPY --from=build /app/build ./build
COPY package*.json ./
# Remplacer npm ci par npm install
RUN npm install --only=production

# Install serve pour servir les fichiers static
RUN npm install -g serve

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]