# Étape de construction
FROM node:16-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install --no-optional

COPY . .
RUN npm run build

# Étape de production
FROM nginx:alpine

# Copier les fichiers construits
COPY --from=build /app/build /usr/share/nginx/html

# Copier la configuration nginx personnalisée
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]