[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && cd ../frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
run = "cd backend && npm start"
httpPort = 5000

[[services]]
name = "postgres"
type = "postgresql"