# render.yaml
services:
  - type: web
    name: metresurmesure-app
    env: docker
    dockerfilePath: Dockerfile.render
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render utilise le port 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://metresurmesureenligne.onrender.com
      - key: BACKEND_URL
        value: https://metresurmesureenligne.onrender.com

    # Health check - important pour Render
    healthCheckPath: /api/health
    healthCheckTimeout: 120

  # Service de base de données PostgreSQL
  - type: pgsql
    name: metresurmesure-db
    plan: free
    ipAllowList: []
    databaseName: metresurmesure
    user: metresuser