# render.yaml
services:
  # Service principal (backend + frontend)
  - type: web
    name: metresurmesure-app
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: FRONTEND_URL
        value: https://metresurmesureenligne.onrender.com
      - key: BACKEND_URL
        value: https://metresurmesureenligne.onrender.com
    domains:
      - metresurmesureenligne.onrender.com

  # Base de données PostgreSQL
  - type: pg
    name: metresurmesure-db
    plan: free
    ipAllowList: []
    databaseName: metresurmesure
    user: metresuser