services:
  # Service Web (Frontend)
  - type: web
    name: metresurmesure-web
    env: docker
    dockerfilePath: ./frontend/Dockerfile.render
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://metresurmesureenligne.onrender.com/api
    port: 3000

  # Service API (Backend)
  - type: web
    name: metresurmesure-api
    env: docker
    dockerfilePath: ./backend/Dockerfile.render
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromService:
          type: postgres
          name: metresurmesure-db
          property: host
      - key: DB_PORT
        fromService:
          type: postgres
          name: metresurmesure-db
          property: port
      - key: DB_NAME
        fromService:
          type: postgres
          name: metresurmesure-db
          property: database
      - key: DB_USER
        fromService:
          type: postgres
          name: metresurmesure-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: metresurmesure-db
          property: password
      - key: JWT_SECRET
        value: 02a1cc8cfba732c5df138a76f718c2c5685994399a0d735c0f45ff0a441bd0abfc2fe67d133c2562733e2b2a622e2bea03c12bef3d133f0de53a2843fcdf9a72
      - key: FRONTEND_URL
        value: https://metresurmesureenligne.onrender.com
    port: 5000

  # Service Database (PostgreSQL)
  - type: postgres
    name: metresurmesure-db
    plan: free
    ipAllowList: []
    databaseName: metresurmesure
    user: metresuser