# render.yaml
services:
  - type: web
    name: metresurmesure-app
    env: docker
    dockerfilePath: Dockerfile.render
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://metresurmesureenligne.onrender.com
      - key: BACKEND_URL
        value: https://metresurmesureenligne.onrender.com

    # Configuration de la base de données
    databases:
      - name: metresurmesure-db
        databaseName: metresurmesure
        user: metresuser
        plan: free

    # Health check
    healthCheckPath: /api/health
    initialDeployHook: echo "Déploiement initial en cours..."

  # Service de base de données PostgreSQL
  - type: pgsql
    name: metresurmesure-db
    plan: free
    ipAllowList: []
    databaseName: metresurmesure
    user: metresuser

# Redirections
routes:
  - type: redirect
    source: /api/*
    destination: https://metresurmesureenligne.onrender.com/api/:splat
    status: 301